name: CHATGPT2
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Clone OpenWrt
      run: |
        git clone https://github.com/openwrt/openwrt.git
        cd openwrt
        make defconfig
        cd ..
        mv openwrt/* ./
        rm -rf openwrt/
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libncurses5-dev libssl-dev unzip gawk zlib1g-dev git subversion
    - name: Create .config
      run: |
        touch openwrt/.config
    - name: Copy .config
      run: |
        cp .config .config.bak
        cp openwrt/.config openwrt/.config.bak
        cp openwrt/.config .config
    - name: Build OpenWrt
      working-directory: ./openwrt
      run: |
        make -j$(nproc)
    - name: Upload firmware
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: openwrt-firmware
        path: openwrt/bin/targets/*
