name: CHATGPT2
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
      - name: Configure
        run: |
          make defconfig
          make menuconfig
      - name: Build
        run: |
          make -j$(nproc) # 使用所有可用的 CPU 核心加速编译
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt firmware
          path: ./bin/targets/
