name: CHATGPT0

on:
  repository_dispatch:
  workflow_dispatch:
env:
  REPO_URL: https://github.com/openwrt/openwrt
  REPO_BRANCH: master
  CONFIG_FILE: .config
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx-ucl libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget curl swig rsync ccache

      - name: Clone source code
        working-directory: /build_dir
        run: |
          df -hT $PWD
          git clone $REPO_URL -b $REPO_BRANCH openwrt
          ln -sf /build_dir/openwrt $GITHUB_WORKSPACE/openwrt
      
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ./openwrt/build_dir
            ./openwrt/staging_dir
          key: ${{ runner.os }}-${{ matrix.profile }}-${{ hashFiles('**/openwrt/feeds.conf') }}
      
      - name: Clone OpenWrt feeds
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Apply custom configuration
        run: |
          [ -e files ] && mv files openwrt/files
          [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
          
      - name: Compile firmware
        run: |
          export PATH="/usr/lib/ccache:$PATH"
          export CCACHE_DIR=$HOME/.ccache
          export CCACHE_MAXSIZE=5G
          make -j$(nproc) V=s

      - name: Generate info file
        run: |
          echo "Build date: $(date)" > info.txt
          echo "Device model: $(cat .config | grep CONFIG_TARGET_DEVICE_NAME= | cut -d '=' -f 2)" >> info.txt
          echo "Installed packages:" >> info.txt
          cat .config | grep '=y' | cut -d '=' -f 1 | sed 's/CONFIG_PACKAGE_//g' >> info.txt

      - name: Upload firmware and info file
        uses: softprops/action-gh-release@v1
        with:
          name: OpenWrt Firmware
          tag_name: openwrt-main
          body: This is a custom firmware built by GitHub Actions.
          files: |
            bin/targets/*/*/*.bin
            info.txt
