name: OpenWrt Compile

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup OpenWrt
        run: |
          git clone https://github.com/openwrt/openwrt.git
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          cp ../.config .config
        env:
          CONFIG_TARGET_x86_64: y # Select the target architecture
      - name: Compile OpenWrt
        run: |
          cd openwrt
          make -j$(nproc) V=s
      - name: Upload Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./openwrt/bin/targets/$CONFIG_TARGET_x86_64/generic/openwrt-$CONFIG_VERSION-x86-64-generic-squashfs-combined.img.gz
          asset_name: openwrt-$CONFIG_VERSION-x86-64-generic-squashfs-combined.img.gz
          asset_content_type: application/octet-stream
        env:
          CONFIG_VERSION: ${{ env.CONFIG_VERSION }} # Set version number
```

这段代码使用GitHub Actions进行编译和发布。它会在每次代码更新时重新编译，然后将编译结果发布为release。

您只需要在提交代码时在根目录下放置一个名为.config的文件，里面包含您的自定义编译参数。同时您需要在GitHub仓库的Secrets中添加名为`CONFIG_VERSION`的环境变量，用于指定版本号。

在编译完成后，将会上传一个名为`openwrt-$CONFIG_VERSION-x86-64-generic-squashfs-combined.img.gz`的文件作为release发布。
